
-- BarberBook Pro 数据库初始化脚本
-- 平台: PostgreSQL (Supabase)

-- 2. 创建理发师表 (App Barbers)
CREATE TABLE IF NOT EXISTS app_barbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  rating FLOAT DEFAULT 5.0,
  image TEXT,
  status TEXT DEFAULT 'active',
  specialties TEXT[],
  schedule INTEGER[],
  experience INTEGER DEFAULT 1,
  service_count INTEGER DEFAULT 0,
  bio TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. 创建顾客表 (App Customers)
CREATE TABLE IF NOT EXISTS app_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  real_name TEXT,
  phone TEXT NOT NULL UNIQUE,
  email TEXT,
  avatar TEXT,
  password_hash TEXT,
  vouchers INTEGER DEFAULT 0, -- New field for vouchers
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 修复：如果表已存在但缺少新字段
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_customers' AND column_name = 'vouchers') THEN
        ALTER TABLE app_customers ADD COLUMN vouchers INTEGER DEFAULT 0;
    END IF;
END $$;

-- 4. 创建预约记录表 (App Appointments)
CREATE TABLE IF NOT EXISTS app_appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  barber_name TEXT,
  service_name TEXT,
  date_str TEXT,
  time_str TEXT,
  price NUMERIC,
  status TEXT DEFAULT 'pending',
  used_voucher BOOLEAN DEFAULT false, -- New field
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_appointments' AND column_name = 'used_voucher') THEN
        ALTER TABLE app_appointments ADD COLUMN used_voucher BOOLEAN DEFAULT false;
    END IF;
END $$;

-- (其余表定义保持不变...)
CREATE TABLE IF NOT EXISTS app_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT,
  role TEXT,
  action TEXT,
  details TEXT,
  type TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS app_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  duration INTEGER NOT NULL,
  icon TEXT DEFAULT 'content_cut',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS app_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL,
  barber_name TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  attitude_rating INTEGER DEFAULT 5,
  skill_rating INTEGER DEFAULT 5,
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 策略设置 (保持不变)
ALTER TABLE app_barbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for app_barbers" ON app_barbers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_customers" ON app_customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_appointments" ON app_appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_logs" ON app_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_settings" ON app_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_services" ON app_services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_ratings" ON app_ratings FOR ALL USING (true) WITH CHECK (true);
