-- BarberBook Pro 数据库初始化脚本
-- 平台: PostgreSQL (Supabase)

-- 1. 启用必要的扩展 (如果需要)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. 创建理发师表 (App Barbers)
CREATE TABLE IF NOT EXISTS app_barbers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  rating FLOAT DEFAULT 5.0,
  image TEXT,
  status TEXT DEFAULT 'active', -- active (在职), busy (忙碌), rest (休息)
  specialties TEXT[], -- 擅长技能数组
  schedule INTEGER[], -- 排班日期数组 (例如: [1,2,3,4,5])
  experience INTEGER DEFAULT 1, -- 从业经验(年)
  service_count INTEGER DEFAULT 0, -- 服务次数 (可作为缓存字段，主要动态计算)
  bio TEXT DEFAULT '', -- 个人简介
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 关键修复：如果表已存在但缺少新字段，手动添加它
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_barbers' AND column_name = 'schedule') THEN
        ALTER TABLE app_barbers ADD COLUMN schedule INTEGER[];
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_barbers' AND column_name = 'experience') THEN
        ALTER TABLE app_barbers ADD COLUMN experience INTEGER DEFAULT 1;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_barbers' AND column_name = 'service_count') THEN
        ALTER TABLE app_barbers ADD COLUMN service_count INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_barbers' AND column_name = 'bio') THEN
        ALTER TABLE app_barbers ADD COLUMN bio TEXT DEFAULT '';
    END IF;
END $$;

-- 3. 创建顾客表 (App Customers)
CREATE TABLE IF NOT EXISTS app_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  real_name TEXT,
  phone TEXT NOT NULL UNIQUE,
  email TEXT,
  avatar TEXT,
  password_hash TEXT, -- 实际生产中应加密存储
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. 创建预约记录表 (App Appointments)
CREATE TABLE IF NOT EXISTS app_appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  barber_name TEXT,
  service_name TEXT,
  date_str TEXT,
  time_str TEXT,
  price NUMERIC,
  status TEXT DEFAULT 'pending', -- pending (待确认), confirmed (已确认), checked_in (已签到), completed (已完成), cancelled (已取消)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. 创建系统日志表 (App Logs)
CREATE TABLE IF NOT EXISTS app_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT, -- 操作人姓名
  role TEXT, -- 操作人角色 (顾客/管理员)
  action TEXT, -- 简短操作描述
  details TEXT, -- 详细描述
  type TEXT, -- 日志类型: info, warning, danger
  avatar TEXT, -- 操作人头像URL
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. 创建全局配置表 (App Settings)
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. 创建服务套餐表 (App Services)
CREATE TABLE IF NOT EXISTS app_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  duration INTEGER NOT NULL, -- 分钟
  icon TEXT DEFAULT 'content_cut',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. 创建评分表 (App Ratings)
CREATE TABLE IF NOT EXISTS app_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT NOT NULL,
  barber_name TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  rating INTEGER NOT NULL, -- 综合评分 (Overall)
  attitude_rating INTEGER DEFAULT 5, -- 新增：服务态度
  skill_rating INTEGER DEFAULT 5, -- 新增：技术水平
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 手动迁移：添加新评分字段
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_ratings' AND column_name = 'attitude_rating') THEN
        ALTER TABLE app_ratings ADD COLUMN attitude_rating INTEGER DEFAULT 5;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'app_ratings' AND column_name = 'skill_rating') THEN
        ALTER TABLE app_ratings ADD COLUMN skill_rating INTEGER DEFAULT 5;
    END IF;
END $$;

-- 9. 插入初始种子数据 (仅当表为空时)

-- 理发师数据
INSERT INTO app_barbers (name, title, rating, status, specialties, schedule, image, experience, bio)
SELECT 'Marcus K.', '美式渐变 / 刻痕', 4.9, 'active', ARRAY['美式渐变', '刻痕'], ARRAY[1,2,3,4,5,8,9,10,11,12], 'https://lh3.googleusercontent.com/aida-public/AB6AXuASZI54tUmbDSYe5gS24e3PgOMrI9qj3GqCIEsupdXwc_RqEBRxxdeTzuQ3J0BROacciMi8-E7ETF5xeF2c2Uk4cf7YG5pilwN59DTPHgqMFtmR-BKshgwP10w2kJSINs_ypgvRDwU3w6nM3XlqoTe2P00EUzVesNcHEhim30CLfIwvsP3__IjMVSrLxerwxTk_9QTAUp9wDxhQiUOSQBM247evrYwIqH808FQf91hnQpmGCY8fFpkv8bZ_2SuikN86EqZhUYAYaRc', 8, 'Marcus 拥有8年高端沙龙经验，擅长各类美式复古油头及渐变造型。他的剪裁风格硬朗干练，深受商务男士喜爱。'
WHERE NOT EXISTS (SELECT 1 FROM app_barbers LIMIT 1);

INSERT INTO app_barbers (name, title, rating, status, specialties, schedule, image, experience, bio)
SELECT 'James L.', '经典剪裁 / 造型', 4.8, 'active', ARRAY['经典剪裁', '造型'], ARRAY[3,4,5,6,7,10,11,12,13,14], 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1qwvlDy5vm9u_b33_rfD-P40Tj3GDKG0BNW3yV3q6xsmoWSeF97hNH2lUiW2hPUuOombMFpnxNvcaTI3fvuVnlFjtiUQiAPARwitCM7fkkOmGhqU45Tbfv2ctMYXUcYuJog4zB8RNrPbkTdkcJVWtuV76N-kCOflrxai1WG_Ugv2XKZ674N23ONPrmzVGCM84SUkgpRzXQw-w7-ygvF6JovNcvEb3vxZjcdJvYqoeV8QJiVFDljKvMKL_L7dDIwrIvQXwOquUvYg', 6, 'James 以细腻的日式剪裁见长，注重发型的空气感和线条流畅度。他善于根据头型特点进行修饰，打造自然易打理的日常造型。'
WHERE NOT EXISTS (SELECT 1 FROM app_barbers WHERE name = 'James L.');

INSERT INTO app_barbers (name, title, rating, status, specialties, schedule, image, experience, bio)
SELECT 'Victor Z.', '韩式纹理 / 染烫', 4.7, 'rest', ARRAY['纹理烫', '色彩设计'], ARRAY[1,3,5,7,9,11,13,15], 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKrSAmGdbivuGTmKJpJ0Uh6duJgkmTs2t0bKqF-97DEWpixi26Ccq815F0QH1osFHIGEtJn8EcJcncboVwXpxHzscJWrU-k1LgdZKE8obzNYOx8dNkwzSqBpp3tT8BdUQkxBcQ4nOl-zeENdRwcJlVsltNhSagqhspDeRVDRqH6V1xCzuomXMaKcfpuA2-kmVqmXUpHfkJUrNws1PYl-PhjRaNGcA0O8JNq_EmV8gM7GTu1JOL_TkGs9SK8OudR4LC21rylR1G_ao', 5, 'Victor 是色彩与纹理的大师，专注于韩式潮流烫发和创意染发。他紧跟时尚趋势，能为您设计出最具个性的前卫造型。'
WHERE NOT EXISTS (SELECT 1 FROM app_barbers WHERE name = 'Victor Z.');

-- 默认系统配置
INSERT INTO app_settings (key, value)
VALUES ('global_config', '{"openTime": "09:00", "closeTime": "21:00", "serviceDuration": 45, "maxAppointments": 24}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- 默认服务套餐
INSERT INTO app_services (name, price, duration, icon)
SELECT '标准男士精剪', 88, 45, 'content_cut'
WHERE NOT EXISTS (SELECT 1 FROM app_services WHERE name = '标准男士精剪');

INSERT INTO app_services (name, price, duration, icon)
SELECT '高级总监设计', 128, 60, 'face'
WHERE NOT EXISTS (SELECT 1 FROM app_services WHERE name = '高级总监设计');

INSERT INTO app_services (name, price, duration, icon)
SELECT '尊享洗剪吹护', 168, 90, 'spa'
WHERE NOT EXISTS (SELECT 1 FROM app_services WHERE name = '尊享洗剪吹护');

INSERT INTO app_services (name, price, duration, icon)
SELECT '潮流染烫套餐', 388, 120, 'palette'
WHERE NOT EXISTS (SELECT 1 FROM app_services WHERE name = '潮流染烫套餐');

-- 10. 配置 Row Level Security (RLS) 策略
ALTER TABLE app_barbers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all operations for app_barbers" ON app_barbers;
DROP POLICY IF EXISTS "Allow all operations for app_customers" ON app_customers;
DROP POLICY IF EXISTS "Allow all operations for app_appointments" ON app_appointments;
DROP POLICY IF EXISTS "Allow all operations for app_logs" ON app_logs;
DROP POLICY IF EXISTS "Allow all operations for app_settings" ON app_settings;
DROP POLICY IF EXISTS "Allow all operations for app_services" ON app_services;
DROP POLICY IF EXISTS "Allow all operations for app_ratings" ON app_ratings;

CREATE POLICY "Allow all operations for app_barbers" ON app_barbers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_customers" ON app_customers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_appointments" ON app_appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_logs" ON app_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_settings" ON app_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_services" ON app_services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for app_ratings" ON app_ratings FOR ALL USING (true) WITH CHECK (true);

-- 11. [后端云端化] 预约自动清理函数 (Cloud Function)
CREATE OR REPLACE FUNCTION cancel_expired_appointments()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    appt RECORD;
    current_year INT := EXTRACT(YEAR FROM (now() AT TIME ZONE 'Asia/Shanghai'))::INT;
    appt_ts TIMESTAMP;
    now_ts TIMESTAMP := (now() AT TIME ZONE 'Asia/Shanghai');
BEGIN
    FOR appt IN
        SELECT id, date_str, time_str, customer_name
        FROM app_appointments
        WHERE status IN ('pending', 'confirmed')
    LOOP
        BEGIN
            -- 解析存储为字符串的日期 (例如: "10月24日", "14:00")
            -- 假设为当前年份
            appt_ts := make_timestamp(
                current_year,
                (substring(appt.date_str from '(\d+)月'))::INT,
                (substring(appt.date_str from '(\d+)日'))::INT,
                (split_part(appt.time_str, ':', 1))::INT,
                (split_part(appt.time_str, ':', 2))::INT,
                0.0
            );

            -- 检查是否过期 (超时 15 分钟)
            IF now_ts > (appt_ts + interval '15 minutes') THEN
                UPDATE app_appointments
                SET status = 'cancelled'
                WHERE id = appt.id;

                INSERT INTO app_logs ("user", role, action, details, type, created_at)
                VALUES (
                    'System (Cloud)',
                    'system',
                    '自动取消违约',
                    format('自动取消超时预约 #%s (顾客: %s)', appt.id, appt.customer_name),
                    'warning',
                    now()
                );
            END IF;
        EXCEPTION WHEN OTHERS THEN
            -- 忽略解析错误的旧数据
            RAISE NOTICE 'Error processing appointment %: %', appt.id, SQLERRM;
        END;
    END LOOP;
END;
$$;

-- 12. [后端云端化] 尝试启用 pg_cron 定时任务 (需要数据库扩展支持)
-- 注意: 在 Supabase Dashboard -> Database -> Extensions 中需启用 pg_cron
DO $$
BEGIN
    -- 尝试创建扩展 (如果不允许会报错，忽略即可)
    BEGIN
        CREATE EXTENSION IF NOT EXISTS pg_cron;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'pg_cron extension not available or permission denied.';
    END;

    -- 如果扩展存在，配置定时任务 (每分钟运行一次)
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        PERFORM cron.schedule('auto_cancel_expired', '* * * * *', 'SELECT cancel_expired_appointments()');
    END IF;
END $$;
